events {}

http {
    server {
        listen 80;

        location /cams/ {
            proxy_pass http://cams-container:8000/;
        }

        location /procurement/ {
            proxy_pass http://procurement-container:8000/;
        }

        location /4sight/ {
            proxy_pass http://4sight-container:8000/;
        }
    }
}